node_id: node5
data_dir: ./data/node5
raft_addr: :5005
http_addr: :8085
peers:
  - localhost:5001
  - localhost:5002
  - localhost:5003
  - localhost:5004
election_timeout_min: 150ms
election_timeout_max: 300ms
heartbeat_interval: 50ms
snapshot_threshold: 10000
